import {RenderBenchmark} from './perf-benchmark.js';
import {CrowdBatch} from './crowd-batch.js';
import {compactGlass} from './compact-glass.js';
import {applyMapCorrections} from '../sim/map-corrections.js';
import {setupAtmosphere} from './atmosphere.js';
import {DrivingEffects} from './driving-effects.js';
import {loadMap} from '../data/load-map.js';
import {MultiplayerClient} from '../net/client.js';
import {PLAY_BOUNDS,MAP_BOUNDS} from '../sim/bounds.js';
import {advanceCar} from '../sim/player-step.js';
import {DrivingInput} from './input.js';
import {EngineAudio} from './audio.js';
import {disposeObject} from './dispose.js';
import {NPC_VEHICLES,HELICOPTER,chooseTrafficStyle,createNPCCar,createHelicopter} from './modern-vehicles.js';
import {updateTurbo,helicopterStep,helicopterPads,roadCorridor,pursuitTarget,pedestrianIntent} from '../sim/modern-driving.js';
import {Trams} from './tram.js';
import {Incidents,impactResponse} from './incidents.js';
import {CameraRig} from '../sim/camera-rig.js';
import {TrafficSignals,lanePoint,trafficSpeed} from './traffic.js';
import {applyCityData,Districts,DISTRICTS} from '../sim/districts.js';
import * as THREE from '../../dist/vendor/three.module.js';
import {CityWorld,PLACES,createCar,createPerson} from './world.js';
import {FixedClock,slideMove,vehicleBlocked,cameraBoom} from '../sim/movement.js';
import {Terrain, WaterRecovery, safeDryRoad} from '../sim/terrain.js';
import {VEHICLES,isBike,createVehicle,createRider,vehiclesOverlap} from './vehicles.js';
import {BuildingModels} from './building-models.js';
import {clamp,dist,angleDiff,collides,makeRoadGraph,nearestRoad,nearestOnSegment,roadRoute} from '../sim/core.js';

const $=s=>document.getElementById(s);
function placeFeet(mesh,x,y,z){mesh.position.set(x,y-(mesh.userData.soleHeight||0),z);}
const state={ready:false,started:false,paused:false,mode:'foot',x:-150,z:-49,y:0,yaw:-.5,speed:0,vy:0,health:100,money:0,wanted:0,escape:0,busted:0,car:null,mission:null,waypoint:null,route:[],camera:0,quality:'medium',sound:false,elapsed:0,distance:0,jobs:0};
const benchmark=location.search?.includes('benchmark=1')?new RenderBenchmark():null;
if(benchmark){let seed=123456789;Math.random=()=>{seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/4294967296;};}
let crowd=null;let drivingEffects=null;let multiplayer=null;const remoteMeshes=new Map();
const cameraRig=new CameraRig();let signals,trams,incidents;const waterRecovery=new WaterRecovery();let terrain,districts,mapReady=null,mapStream=null;
const clock=new FixedClock();let modelLayer,renderAlpha=1,previousPose=null;const previousActors=new Map();
function visualPose(){if(multiplayer?.connected&&multiplayer.prediction)return multiplayer.prediction.visual(0);if(!previousPose||previousPose.mode!==state.mode||dist(previousPose,state)>10)return state;return {x:THREE.MathUtils.lerp(previousPose.x,state.x,renderAlpha),z:THREE.MathUtils.lerp(previousPose.z,state.z,renderAlpha),y:THREE.MathUtils.lerp(previousPose.y,state.y,renderAlpha)};}
const keys=new Set(),cars=[],people=[],cops=[],integratedBuildingTiles=new Set(),buildingTileQueue=[];let data,world,graph,patrolGraph,renderer,scene,camera,sun,player,marker,mapBase,mapCtx,frameTime=0,lastUi=0,toastUntil=0,collisionCooldown=0,followYaw=0,camOrbit=0,camPitch=.38,drag=null,jumpPressed=false,engineAudio=null,frame=0,buildingStreamCell='',buildingStreamPending=false,nextBuildingIntegration=0,travelPending=false;
const drivingInput=new DrivingInput(keys);let currentInput={forward:0,turn:0,brake:false,boost:false};const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
const canvas=$('world'),mini=$('minimap'),miniCtx=mini.getContext('2d');
const minBounds=MAP_BOUNDS;
function save(){try{localStorage.setItem('padova-game-v2',JSON.stringify({money:state.money,jobs:state.jobs,quality:state.quality}));}catch{}}
try{const s=JSON.parse(localStorage.getItem('padova-game-v2')||'{}');state.money=Number.isFinite(s.money)?Math.max(0,s.money):0;state.jobs=Number.isFinite(s.jobs)?s.jobs:0;state.quality=['low','medium','high'].includes(s.quality)?s.quality:'medium';}catch{}
function toast(t,seconds=3.5){$('toast').textContent=t;$('toast').hidden=false;toastUntil=state.elapsed+seconds;}
function progress(n,text){$('loadingBar').style.width=n+'%';$('loadingText').textContent=text;}
function yieldFrame(){return new Promise(resolve=>setTimeout(resolve,16));}
function integrateBuildingTile(tile){if(!tile||integratedBuildingTiles.has(tile.key))return;const buildings=world.addBuildings(tile.buildings);districts.addBuildings(buildings);integratedBuildingTiles.add(tile.key);mapStream?.release(tile.key);}
function enqueueBuildingTiles(tiles){const queued=new Set(buildingTileQueue.map(tile=>tile.key));for(const tile of tiles)if(!integratedBuildingTiles.has(tile.key)&&!queued.has(tile.key)){buildingTileQueue.push(tile);queued.add(tile.key);}}
async function requestBuildingTiles(x,z,radius=1600){if(!mapStream||buildingStreamPending)return;const size=mapStream.manifest?.size||400,cell=Math.floor(x/size)+','+Math.floor(z/size);if(cell===buildingStreamCell)return;buildingStreamCell=cell;buildingStreamPending=true;try{enqueueBuildingTiles(await mapStream.loadAround(x,z,radius));}catch(error){buildingStreamCell='';console.warn('Building stream delayed',error);}finally{buildingStreamPending=false;}}
function pumpBuildingTiles(time){if(!buildingTileQueue.length||time<nextBuildingIntegration)return;integrateBuildingTile(buildingTileQueue.shift());nextBuildingIntegration=time+60;}
async function prepareTravelTiles(p){if(!mapStream)return;const tiles=await mapStream.loadAround(p.x,p.z,1100),keys=new Set(tiles.map(tile=>tile.key));for(const tile of tiles)integrateBuildingTile(tile);for(let i=buildingTileQueue.length-1;i>=0;i--)if(keys.has(buildingTileQueue[i].key))buildingTileQueue.splice(i,1);}

function compactCar(group){const positions=[],colors=[],normals=[];group.updateMatrixWorld(true);const inverseRoot=group.matrixWorld.clone().invert();const v=new THREE.Vector3(),n=new THREE.Vector3();const remove=[];group.traverse(o=>{if(!o.isMesh||o.material.transparent)return;const g=o.geometry,ind=g.index?.array,p=g.attributes.position,no=g.attributes.normal,c=o.material.color,nm=new THREE.Matrix3().getNormalMatrix(new THREE.Matrix4().multiplyMatrices(inverseRoot,o.matrixWorld));for(let j=0;j<(ind?.length||p.count);j++){const i=ind?ind[j]:j;v.fromBufferAttribute(p,i).applyMatrix4(o.matrixWorld).applyMatrix4(inverseRoot);n.fromBufferAttribute(no,i).applyMatrix3(nm).normalize();positions.push(v.x,v.y,v.z);normals.push(n.x,n.y,n.z);colors.push(c.r,c.g,c.b);}remove.push(o);});for(const o of remove)o.parent?.remove(o);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const mesh=new THREE.Mesh(g,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.65}));mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);compactGlass(group);return group;}
const vehicleStyles=[...Object.keys(NPC_VEHICLES),'mito','cinquecento','motorcycle','truck','scooter','sedan','sport','compact','wagon','utility'];
function poseVehicle(c){if(c.spec.aircraft){c.mesh.position.set(c.x,c.y??terrain.height(c.x,c.z),c.z);c.mesh.rotation.set(-c.speed*.002,c.yaw,0,'YXZ');return;}c.y=terrain.height(c.x,c.z,c.y);c.mesh.position.set(c.x,c.y,c.z);const pitch=terrain.slope(c.x,c.z,c.yaw,c.spec.wheelbase,c.y);c.pitch=(c.pitch??pitch)+(pitch-(c.pitch??pitch))*.18;c.mesh.rotation.set(c.pitch,c.yaw,0,'YXZ');if(c.rider)c.rider.visible=c===state.car||!c.parked;}
function addCar(x,z,yaw=0,police=false,parked=false,requestedStyle=null){
 const palette=['#a92731','#567e7e','#c87358','#e4dbba','#48677b','#8f9b6f','#9b4e4a','#59606b','#d0d3ce'],index=cars.length,style=police?'sedan':requestedStyle||vehicleStyles[index%vehicleStyles.length],color=police?'#193b54':palette[index%palette.length];
 const m=style==='airone'?createHelicopter():compactCar(NPC_VEHICLES[style]?createNPCCar(style,color):['mito','cinquecento','motorcycle','scooter','truck'].includes(style)?createVehicle(style,color):createCar(color,police,style)),spec=VEHICLES[style];
 const c={x,z,yaw,speed:0,health:100,mesh:m,police,parked,target:null,prev:null,name:police?'Polizia':spec.name,style,spec,path:[],pathIndex:0,routeAt:0,stuck:0};
 if(isBike(style)){c.rider=createRider();m.add(c.rider);}
 poseVehicle(c);scene.add(m);
 if(police){const mat=new THREE.MeshBasicMaterial({color:'#419cff'});const lamp=new THREE.Mesh(new THREE.BoxGeometry(.4,.18,.32),mat);lamp.position.set(-.35,1.84,-.15);m.add(lamp);c.lamp=lamp;c.beacon=new THREE.PointLight('#298aff',0,13,2);c.beacon.position.set(0,2,0);m.add(c.beacon);cops.push(c);}else cars.push(c);return c;
}
function dryRoad(pos,spec=null,ignore=state.car){return safeDryRoad(pos,graph,world.collision,terrain,spec,p=>![...cars,...cops].some(c=>c!==ignore&&c.mesh.visible&&dist(c,p)<(c.spec.length+(spec?.length||1))/2+1));}
function vehiclesMenu(){if(multiplayer?.connected){toast('Online free roam uses the Milano 955. Leave the room to change vehicles.');return;}if(!state.started||waterRecovery.active||incidents?.recovery)return;showMenu('Choose a vehicle','<p class="about-copy">Bring a vehicle to a clear road nearby. E to get in. V opens this menu.</p><div class="activities">'+['mito','cinquecento','motorcycle','scooter','truck'].map(type=>'<button class="activity" data-vehicle="'+type+'"><span><b>'+VEHICLES[type].name+'</b><small>'+Math.round(VEHICLES[type].max*3.6)+' km/h · '+VEHICLES[type].length+' m</small></span></button>').join('')+'</div>');document.querySelectorAll('[data-vehicle]').forEach(button=>button.onclick=()=>{
 const type=button.dataset.vehicle,spec=VEHICLES[type];let p=null;
 for(const offset of [12,24,40,70]){const candidate=dryRoad({x:state.x+Math.sin(state.yaw)*offset,z:state.z+Math.cos(state.yaw)*offset},spec);if(candidate&&dist(candidate,state)>spec.length/2+3&&![...cars,...cops].some(c=>c.mesh.visible&&dist(c,candidate)<(c.spec.length+spec.length)/2+2)){p=candidate;break;}}
 if(!p){toast('No clear space nearby. Move to a wider road.');return;}
 let c=cars.find(c=>c!==state.car&&c.style===type);if(!c)c=addCar(p.x,p.z,p.yaw,false,true,type);c.x=p.x;c.z=p.z;c.y=p.y??terrain.height(p.x,p.z);c.yaw=p.yaw;c.speed=0;c.health=100;c.parked=true;c.mesh.visible=true;poseVehicle(c);previousActors.delete(c.mesh);closeDialogs();state.waypoint={x:c.x,z:c.z,name:c.name};routeTo(state.waypoint);toast(c.name+' is waiting '+Math.round(dist(state,c))+' m away. Follow the marker.',5);
 });}
function goodNearbyNode(pos,minD=50,maxD=500,spec=null,style=null){const candidates=[],seen=new Set();let total=0;
 for(const s of graph.index.near(pos.x,pos.z,maxD)){const road=s.road;if(!s.connected||road.w<(spec?.length>6?7:spec?4:0)||['no','private'].includes(road.access)||spec&&road.k==='pedestrian'||!spec&&/motorway|trunk/.test(road.k))continue;
  for(const id of [s.a,s.b]){if(seen.has(id))continue;seen.add(id);const n=graph.nodes[id],d=dist(n,pos);if(d<=minD||d>=maxD||!n.edges.length)continue;
   const zone=DISTRICTS[districts?.at(n.x,n.z,road)||'urban'],weight=spec?zone.traffic*(style?(zone.vehicles.includes(style)?3:.1):1):zone.people;
   if(weight<=0)continue;total+=weight;candidates.push({id,end:total});}}
 const r=Math.random()*total;return candidates.find(p=>r<p.end)?.id??null;
}
const trafficModels=new Map();
function restyleTraffic(c,zone){if(c.police||c.parked)return;const legacy=DISTRICTS[zone].vehicles,style=Math.random()<.2?legacy[Math.floor(Math.random()*legacy.length)]:chooseTrafficStyle(zone);if(style===c.style)return;
 if(!trafficModels.has(style)){const color=['#a92731','#667d7d','#c9c1ac','#687688'][Math.max(0,vehicleStyles.indexOf(style))%4],m=compactCar(NPC_VEHICLES[style]?createNPCCar(style,color):['mito','cinquecento','scooter','motorcycle','truck'].includes(style)?createVehicle(style,color):createCar(color,false,style));trafficModels.set(style,m);}
 const old=c.mesh;scene.remove(old);previousActors.delete(old);c.mesh=trafficModels.get(style).clone(true);scene.add(c.mesh);c.style=style;c.spec=VEHICLES[style];c.name=c.spec.name;c.rider=null;if(isBike(style)){c.rider=createRider();c.mesh.add(c.rider);}
}
function placeTraffic(c,minD=100,maxD=550){const id=goodNearbyNode(state,minD,maxD,c.spec,c.style);if(id===null){c.mesh.visible=false;return;}const n=graph.nodes[id];restyleTraffic(c,districts?.at(n.x,n.z,n.edges[0]?.road)||'urban');c.x=n.x;c.z=n.z;c.prev=id;c.target=n.edges[Math.floor(Math.random()*n.edges.length)]?.id;c.stuck=0;c.speed=0;c.driver=.8+Math.random()*.35;if(c.target!==undefined){const t=graph.nodes[c.target];c.yaw=Math.atan2(t.x-c.x,t.z-c.z);}const safe=dryRoad(c,c.spec,c);if(!safe||[...cars,...cops].some(other=>other!==c&&other.mesh.visible&&dist(c,other)<(c.spec.length+other.spec.length)/2+2)){c.mesh.visible=false;return;}c.x=safe.x;c.z=safe.z;c.yaw=safe.yaw;c.y=terrain.roads.sample(safe.segment.road,c.x,c.z)+.05;c.road=safe.segment.road;const reverse=c.road.oneway===-1;c.prev=reverse?safe.segment.b:safe.segment.a;c.target=reverse?safe.segment.a:safe.segment.b;c.mesh.visible=true;poseVehicle(c);}
function createPopulation(){const initial=dryRoad(state,VEHICLES.mito);if(initial){state.x=initial.x-3*Math.cos(initial.yaw);state.z=initial.z+3*Math.sin(initial.yaw);if(collides(state.x,state.z,.35,world.collision)||!terrain.dry(state.x,state.z,1)){state.x=initial.x;state.z=initial.z;}state.yaw=initial.yaw;addCar(initial.x,initial.z,initial.yaw,false,true,'mito');state.y=terrain.height(state.x,state.z,state.y);waterRecovery.remember(state,terrain);}
 const count=state.quality==='low'?16:state.quality==='high'?48:30;for(let i=0;i<count;i++){const c=addCar(0,0,0,false,i<3);placeTraffic(c,60,520);}
 const population=state.quality==='low'?40:state.quality==='high'?120:72;for(let i=0;i<population;i++){const p={x:0,z:0,yaw:0,seed:i,mesh:createPerson(['#d2b487','#719085','#bc745a','#527789','#c18c77','#6f789b'][i%6],i),at:0};scene.add(p.mesh);people.push(p);placePerson(p);}
 for(const pad of helicopterPads(terrain,world.collision,HELICOPTER)){const c=addCar(pad.x,pad.z,0,false,true,'airone');c.y=pad.y;c.home=pad;c.name+=' · '+pad.name;poseVehicle(c);}
}
function placePerson(p){p.at=state.elapsed+4+Math.random()*8;p.mesh.visible=false;
 for(let attempt=0;attempt<16;attempt++){const id=goodNearbyNode(state,25,240);if(id===null)return;const n=graph.nodes[id],e=n.edges.find(e=>!/motorway|trunk/.test(e.road.k));if(!e)continue;
  const t=graph.nodes[e.id],yaw=Math.atan2(t.x-n.x,t.z-n.z),side=p.seed%2?1:-1,offset=e.road.k==='pedestrian'?1:e.road.w/2+1.25,u=.15+Math.random()*.7;
  const x=n.x+(t.x-n.x)*u+Math.cos(yaw)*offset*side,z=n.z+(t.z-n.z)*u-Math.sin(yaw)*offset*side;
  const zone=DISTRICTS[districts?.at(x,z,e.road)||'urban'];if(Math.random()>Math.min(1,zone.people/1.5))continue;
  if(collides(x,z,.4,world.collision)||!terrain.dry(x,z,.6))continue;
  Object.assign(p,{x,z,y:terrain.height(x,z),yaw,roadYaw:yaw,side,behavior:['destination','stroll','idle','cross','wait','group','runner','wander','avoid','poi'][p.seed%10],crossGoal:null,destination:{x:t.x+Math.cos(yaw)*offset*side,z:t.z-Math.sin(yaw)*offset*side},road:e.road,anchor:{x,z},knockX:0,knockZ:0,spin:0});p.mesh.visible=true;if(p.behavior==='poi'){const poi=PLACES.find(a=>dist(a,p)<40);if(poi)p.destination={x:poi.x,z:poi.z};}p.at=state.elapsed+18+Math.random()*24;
  const color=zone.colors[p.seed%zone.colors.length];if(p.mesh.userData.clothesColor!==color){p.mesh.traverse(o=>{if(o.userData.clothing)o.material.color.set(color);});p.mesh.userData.clothesColor=color;}return;
 }
}

function yieldMapWork(){return new Promise(resolve=>window.requestIdleCallback?window.requestIdleCallback(()=>resolve(),{timeout:80}):setTimeout(resolve,16));}
async function makeMap(){mapBase=document.createElement('canvas');mapBase.width=900;mapBase.height=870;mapCtx=mapBase.getContext('2d');const c=mapCtx,sx=mapBase.width/minBounds.w,sz=mapBase.height/minBounds.h;c.fillStyle='#1d333c';c.fillRect(0,0,mapBase.width,mapBase.height);const path=(p,close=false)=>{c.beginPath();p.forEach((p,i)=>{const x=(p[0]-minBounds.x)*sx,y=(p[1]-minBounds.z)*sz;if(!i)c.moveTo(x,y);else c.lineTo(x,y);});if(close)c.closePath();},batch=async(items,draw,size)=>{for(let i=0;i<items.length;i++){draw(items[i]);if(i&&i%size===0)await yieldMapWork();}};
 await yieldMapWork();await batch(data.areas,a=>{path(a.p,true);c.fillStyle=a.k==='water'?'#33545d':'#284b42';c.fill();},400);await batch(data.water,r=>{path(r.p);c.strokeStyle='#335d69';c.lineWidth=Math.max(1,r.w*sx);c.stroke();},400);c.fillStyle='#33474d';await batch(data.buildings,b=>{path(b.p,true);c.fill();},750);await batch(data.roads,r=>{path(r.p);c.lineWidth=Math.max(.5,r.w*sx);c.strokeStyle=['footway','path','steps'].includes(r.k)?'#405158':'#607278';c.stroke();},500);
}
function drawRoute(ctx,transform,width=3){if(!state.route.length)return;ctx.beginPath();state.route.forEach((p,i)=>{const a=transform(p);if(!i)ctx.moveTo(a.x,a.y);else ctx.lineTo(a.x,a.y);});ctx.strokeStyle='#edbb65';ctx.lineWidth=width;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke();}
function drawMini(){if(!mapBase)return;const c=miniCtx,w=mini.width,h=mini.height,range=state.mode==='car'?530:320,k=w/range;c.fillStyle='#172e38';c.fillRect(0,0,w,h);const mx=(state.x-minBounds.x)/minBounds.w*mapBase.width,my=(state.z-minBounds.z)/minBounds.h*mapBase.height,sw=range/minBounds.w*mapBase.width,sh=h/k/minBounds.h*mapBase.height;c.drawImage(mapBase,mx-sw/2,my-sh/2,sw,sh,0,0,w,h);const tr=p=>({x:(p.x-state.x)*k+w/2,y:(p.z-state.z)*k+h/2});drawRoute(c,tr,5);
 for(const p of PLACES){const t=tr(p);if(t.x>5&&t.x<w-5&&t.y>10&&t.y<h-5){c.fillStyle='#c6b28c';c.beginPath();c.arc(t.x,t.y,4,0,Math.PI*2);c.fill();}}
 for(const c of cars)if(c.spec.aircraft){const t=tr(c);if(t.x>8&&t.x<w-8&&t.y>8&&t.y<h-8){miniCtx.fillStyle='#edbb65';miniCtx.font='bold 14px sans-serif';miniCtx.fillText('H',t.x,t.y);}}
 for(const p of cops){const t=tr(p);c.fillStyle='#76b7ff';c.beginPath();c.arc(t.x,t.y,5,0,Math.PI*2);c.fill();}const target=currentTarget();if(target){const t=tr(target);c.fillStyle='#ffc56a';c.beginPath();c.arc(clamp(t.x,10,w-10),clamp(t.y,10,h-10),7,0,Math.PI*2);c.fill();}
 c.save();c.translate(w/2,h/2);c.rotate(-state.yaw);c.fillStyle='#fff8de';c.strokeStyle='#18323d';c.lineWidth=2;c.beginPath();c.moveTo(0,11);c.lineTo(-7,-7);c.lineTo(0,-3);c.lineTo(7,-7);c.closePath();c.fill();c.stroke();c.restore();c.fillStyle='#bbcbd0';c.font='600 20px system-ui';c.fillText('N',w-28,26);
}
function fullTransform(p){const c=$('fullmap');return {x:(p.x-minBounds.x)/minBounds.w*c.width,y:(p.z-minBounds.z)/minBounds.h*c.height};}
function drawFullMap(){const c=$('fullmap').getContext('2d'),w=$('fullmap').width,h=$('fullmap').height;c.drawImage(mapBase,0,0,w,h);drawRoute(c,fullTransform,3);for(const p of PLACES){const a=fullTransform(p);c.fillStyle='#ffc56a';c.beginPath();c.arc(a.x,a.y,3,0,Math.PI*2);c.fill();}const a=fullTransform(state);c.fillStyle='white';c.strokeStyle='#172e38';c.lineWidth=3;c.beginPath();c.arc(a.x,a.y,8,0,Math.PI*2);c.fill();c.stroke();const target=currentTarget();if(target){const b=fullTransform(target);c.strokeStyle='#ffc56a';c.lineWidth=3;c.beginPath();c.arc(b.x,b.y,10,0,Math.PI*2);c.stroke();c.fillStyle='#ffc56a';c.font='600 19px system-ui';c.fillText('DESTINATION',clamp(b.x+16,5,810),b.y+6);}}
function currentTarget(){return state.mission?.target||state.waypoint;}
function routeTo(target){state.route=target?roadRoute(state,target,graph):[];if(target&&!state.route.length)toast('No connected road route here. Follow the destination marker.');}
function updateMarker(){const t=currentTarget();marker.visible=!!t;if(!t)return;marker.position.set(t.x,terrain.height(t.x,t.z)+.16,t.z);const d=dist(state,t);$('targetDistance').hidden=false;$('targetDistance').textContent=(t.name||'Destination')+' · '+(d>=1000?(d/1000).toFixed(1)+' km':Math.round(d)+' m');}

function toggleVehicle(){if(multiplayer?.connected){toast('Leave the online room to use single-player activities.');return;}if(!state.started||state.paused||waterRecovery.active||incidents?.recovery)return;if(state.mode==='car'){if(Math.abs(state.speed)>7){toast('Slow down before getting out.');return;}const c=state.car;if(c.spec.aircraft&&state.y>terrain.height(state.x,state.z)+.4){toast('Land before leaving the helicopter.');return;}c.turboTime=0;let out=null;for(const a of [Math.PI/2,-Math.PI/2,Math.PI,0]){const p={x:state.x+Math.sin(state.yaw+a)*(Math.abs(Math.sin(a))>.5?c.spec.width/2+1:c.spec.length/2+1),z:state.z+Math.cos(state.yaw+a)*(Math.abs(Math.sin(a))>.5?c.spec.width/2+1:c.spec.length/2+1)};if(!collides(p.x,p.z,.4,world.collision)&&terrain.dry(p.x,p.z,.5)){out=p;break;}}if(!out){toast('No room to get out here.');return;}state.mode='foot';c.parked=true;c.speed=0;c.health=state.health;state.car=null;state.x=out.x;state.z=out.z;state.speed=0;state.lateral=0;state.yawRate=0;state.y=terrain.height(state.x,state.z,state.y);state.vy=0;placeFeet(player,state.x,state.y,state.z);player.visible=true;toast('On foot. E to get back in.');}else{let nearest=null,d=6;for(const c of cars){const dd=dist(state,c);if(c.mesh.visible&&dd<d&&Math.abs(c.speed)<8&&Math.abs((c.y||0)-state.y)<4){nearest=c;d=dd;}}if(!nearest){toast('Walk closer to a parked or slow-moving car.');return;}state.mode='car';state.y=nearest.y??terrain.height(nearest.x,nearest.z);state.vy=0;state.car=nearest;state.x=nearest.x;state.z=nearest.z;state.yaw=nearest.yaw;state.speed=0;state.lateral=0;state.yawRate=0;state.health=nearest.health;nearest.parked=true;player.visible=false;toast(nearest.name+(nearest.spec.aircraft?' · WASD fly · Space climb · Shift descend':' · WASD drive, Space handbrake, Shift boost'),5);}camOrbit=0;followYaw=state.yaw;cameraRig.reset(state.yaw);}
function recover(fromWater=false){
 if(incidents?.recovery)return false;fromWater=fromWater===true;state.knockX=state.knockZ=state.spin=0;
 const origin=fromWater?(waterRecovery.lastDry||state):state,p=dryRoad(origin,state.car?.spec)||dryRoad(PLACES[0],state.car?.spec);if(!p){toast('No clear dry road found. Use the map to travel.');return false;}
 previousPose=null;keys.clear();waterRecovery.reset();document.body.classList.remove('water-fall');state.x=p.x;state.z=p.z;state.yaw=p.yaw;state.speed=0;state.lateral=0;state.yawRate=0;state.y=p.y??terrain.height(p.x,p.z);state.vy=0;state.health=100;
 if(state.car){Object.assign(state.car,{x:p.x,z:p.z,yaw:p.yaw,speed:0,health:100,knockX:0,knockZ:0,spin:0,turboTime:0,y:state.y,vy:0});poseVehicle(state.car);previousActors.delete(state.car.mesh);}
 waterRecovery.remember(state,terrain);world.update(state.x,state.z,true);camera.position.set(state.x-10,state.y+9,state.z-12);followYaw=state.yaw;cameraRig.reset(state.yaw);routeTo(currentTarget());toast(fromWater?'Back on dry land. Water cannot be crossed.':'Back on the road. Vehicle repaired.');return true;
}
function falling(dt){
 const done=waterRecovery.step(dt);state.y=waterRecovery.y;
 if(state.car){state.car.mesh.position.y=state.y;state.car.mesh.rotation.x+=dt*.5;}else placeFeet(player,state.x,state.y,state.z);
 if(done)recover(true);
}
async function travel(p){if(multiplayer?.connected){toast('Leave the online room to use single-player activities.');return;}if(travelPending)return;travelPending=true;try{if(mapStream){toast('Preparing '+p.name+'…');await prepareTravelTiles(p);}previousPose=null;cancelMission(false);clearPolice();const n=dryRoad(p,state.car?.spec);if(!n)return;waterRecovery.reset();document.body.classList.remove('water-fall');state.x=n.x;state.z=n.z;state.yaw=n.yaw;state.speed=0;state.lateral=0;state.yawRate=0;state.y=n.y??terrain.height(state.x,state.z,state.y);state.vy=0;state.health=100;state.waypoint=null;state.route=[];if(state.car){state.car.x=n.x;state.car.z=n.z;state.car.yaw=n.yaw;state.car.speed=0;state.car.health=100;state.car.y=state.y;state.car.turboTime=0;poseVehicle(state.car);previousActors.delete(state.car.mesh);}else{let c=cars.find(c=>c.parked&&!c.spec.aircraft);if(c){const parking=dryRoad({x:n.x+8*Math.sin(n.yaw),z:n.z+8*Math.cos(n.yaw)},c.spec);if(parking){c.x=parking.x;c.z=parking.z;c.yaw=parking.yaw;poseVehicle(c);previousActors.delete(c.mesh);}}}world.update(state.x,state.z,true);for(const c of cars)if(c!==state.car&&!c.parked)placeTraffic(c);people.forEach(placePerson);waterRecovery.remember(state,terrain);camera.position.set(state.x-12,state.y+12,state.z-16);followYaw=state.yaw;cameraRig.reset(state.yaw);buildingStreamCell='';toast('Welcome to '+p.name);closeDialogs();}catch(error){console.warn('Destination tiles unavailable',error);toast('That area could not be prepared. Try again.');}finally{travelPending=false;}}
function ensureCar(){if(state.mode==='car'&&!state.car.spec.aircraft)return true;toast('Get into a car first. A parked car is waiting nearby.');return false;}
const missionTypes={delivery:{title:'Special delivery',desc:'Pick up a parcel, then deliver it across the centre.',reward:'€350'},race:{title:'The Padova run',desc:'Six checkpoints. Five minutes. Your best line.',reward:'€600'},escape:{title:'Lose the tail',desc:'Get the police’s attention, then disappear.',reward:'€500'}};
function safeTarget(p){const n=dryRoad(p);return n?{x:n.x,z:n.z,name:p.name}:p;}
function beginMission(type){if(multiplayer?.connected){toast('Leave the online room to use single-player activities.');return;}if(!ensureCar())return;clearPolice();state.waypoint=null;const now=state.elapsed;if(type==='delivery'){const pickup=safeTarget(PLACES[2]),drop=safeTarget(PLACES[8]);state.mission={type,phase:'pickup',target:pickup,drop,deadline:now+240,title:'A parcel at the piazza',desc:'Reach Piazza delle Erbe and stop in the gold marker to collect the parcel.'};}
 if(type==='race'){const checkpoints=[PLACES[0],PLACES[1],PLACES[2],PLACES[3],PLACES[5],PLACES[8]].map(safeTarget);state.mission={type,phase:'ready',checkpoints,index:0,target:checkpoints[0],deadline:Infinity,title:'Meet at Prato della Valle',desc:'Drive to the start marker. The 5-minute clock starts there.'};}
 if(type==='escape'){state.mission={type,target:null,deadline:now+180,title:'Lose the tail',desc:'Break away from the police. Stay more than 120 m from every patrol for 12 seconds.'};raiseWanted(2);}
 routeTo(currentTarget());closeDialogs();toast(type==='escape'?'The chase is on. Get moving.':'Job accepted. Follow the gold route.');updateMissionUI();}
function cancelMission(notify=true){state.mission=null;state.route=[];if(state.waypoint)routeTo(state.waypoint);if(notify)toast('Activity cancelled.');updateMissionUI();}
function finishMission(reward,message){state.money+=reward;state.jobs++;save();state.mission=null;state.route=[];clearPolice();toast(message+' +€'+reward,6);updateMissionUI();}
function updateMission(dt){const m=state.mission;if(!m)return;if(state.elapsed>m.deadline){toast('Time’s up. Try again from Activities.',5);cancelMission(false);return;}if(m.type==='escape')return;if(!m.target)return;const near=dist(state,m.target)<(m.type==='race'?17:14);if(m.type==='delivery'&&near&&state.mode==='car'&&Math.abs(state.speed)<4){if(m.phase==='pickup'){m.phase='drop';m.target=m.drop;m.title='Take it to Portello';m.desc='The parcel is on board. Deliver it to the gold marker at Portello.';routeTo(m.target);toast('Parcel collected. Next stop: Portello.');}else finishMission(350,'Delivered. Nicely done.');}else if(m.type==='race'&&near&&state.mode==='car'){if(m.phase==='ready'){m.phase='running';m.deadline=state.elapsed+300;m.index=1;m.title='The Padova run';m.desc='Hit every checkpoint before the timer runs out.';toast('GO! First checkpoint: the Santo.');}else{m.index++;toast('Checkpoint '+(m.index-1)+' / 5',1.6);}if(m.index>=m.checkpoints.length){finishMission(600,'Run complete.');return;}m.target=m.checkpoints[m.index];routeTo(m.target);} }
function updateMissionUI(){const m=state.mission;$('missionType').textContent=m?m.type==='race'?'STREET RUN':m.type==='delivery'?'COURIER JOB':'POLICE PURSUIT':'FREE ROAM';$('missionTitle').textContent=m?m.title:'The city is yours.';$('missionDesc').textContent=m?m.desc:'Explore, borrow a car, or pick an activity.';let timer='';if(m&&Number.isFinite(m.deadline)){const s=Math.max(0,Math.ceil(m.deadline-state.elapsed));timer=Math.floor(s/60)+':'+String(s%60).padStart(2,'0');if(m.type==='escape'&&state.escape>0)timer+=' · HIDDEN '+Math.floor(state.escape)+'/12';}else if(m?.type==='race')timer='READY WHEN YOU ARE';$('missionTimer').textContent=timer;}

function clearPolice(){for(const c of cops){scene.remove(c.mesh);previousActors.delete(c.mesh);disposeObject(c.mesh);}cops.length=0;state.wanted=0;state.escape=0;state.busted=0;}
function raiseWanted(level=1){state.wanted=clamp(Math.max(state.wanted,level),0,5);state.escape=0;while(cops.length<Math.min(4,state.wanted+1)){const id=goodNearbyNode(state,95,200,VEHICLES.sedan);if(id===null)break;const n=graph.nodes[id];const spawn=dryRoad(n,VEHICLES.sedan);if(!spawn)break;addCar(spawn.x,spawn.z,spawn.yaw,true);} }
function updatePolice(dt){if(!state.wanted)return;let nearest=Infinity;for(const [patrol,c] of cops.entries()){
 const d=dist(c,state);nearest=Math.min(nearest,d);
 if(c.routeAt<state.elapsed){c.path=roadRoute(c,pursuitTarget(state,patrol,patrolGraph||graph),patrolGraph||graph);c.pathIndex=1;c.routeAt=state.elapsed+1.4+patrol*.25;}
 let target=c.path[c.pathIndex];while(target&&dist(c,target)<Math.max(3,c.speed*.3)){c.pathIndex++;target=c.path[c.pathIndex];}
 if(!target){c.speed=0;c.routeAt=0;poseVehicle(c);continue;}
 const goal=Math.atan2(target.x-c.x,target.z-c.z),diff=angleDiff(goal,c.yaw),newYaw=c.yaw+clamp(diff,-2.4*dt,2.4*dt),limit=Math.abs(diff)>.6?5:clamp(d*.45,5,23+state.wanted*3);
 let desired=limit;for(const other of cops)if(other!==c&&dist(c,other)<7&&Math.abs(angleDiff(Math.atan2(other.x-c.x,other.z-c.z),c.yaw))<.6)desired=0;
 c.speed+=clamp(desired-c.speed,-c.spec.brake*dt,c.spec.accel*dt);
 const nx=c.x+Math.sin(newYaw)*c.speed*dt,nz=c.z+Math.cos(newYaw)*c.speed*dt;
 if(roadCorridor(nx,nz,c,graph,terrain)&&!vehicleBlocked(nx,nz,newYaw,world.collision,c.spec,terrain.height(nx,nz,c.y))){c.x=nx;c.z=nz;c.yaw=newYaw;c.stuck=c.speed<.2?c.stuck+dt:0;}
 else{c.speed=0;c.stuck+=dt;if(!vehicleBlocked(c.x,c.z,newYaw,world.collision,c.spec,c.y))c.yaw=newYaw;}
 if(c.stuck>6){c.routeAt=0;if(d>70){const n=dryRoad(c,c.spec,c);if(n){c.x=n.x;c.z=n.z;c.y=n.y??terrain.roads.sample(n.segment.road,n.x,n.z)+.05;c.yaw=n.yaw;previousActors.delete(c.mesh);}}else{const x=c.x-Math.sin(c.yaw)*dt*2,z=c.z-Math.cos(c.yaw)*dt*2;if(roadCorridor(x,z,c,graph,terrain)&&!vehicleBlocked(x,z,c.yaw,world.collision,c.spec,c.y)){c.x=x;c.z=z;}}if(c.stuck>9)c.stuck=0;}
 poseVehicle(c);c.lamp.visible=Math.sin(state.elapsed*16)>0;c.beacon.intensity=c.lamp.visible?8:0;
 if(d<3&&Math.abs(c.y-state.y)<3&&state.mode==='car'&&collisionCooldown<=0){state.speed*=.65;state.health=Math.max(0,state.health-4);collisionCooldown=.5;}
 }

 if(nearest>120){state.escape+=dt;if(state.escape>=12){const reward=state.mission?.type==='escape';clearPolice();if(reward)finishMission(500,'You lost them.');else toast('Escaped. Back to free roam.',5);}}else state.escape=Math.max(0,state.escape-dt*2);
 if(nearest<7&&(state.mode==='foot'||Math.abs(state.speed)<2))state.busted+=dt;else state.busted=Math.max(0,state.busted-dt);if(state.busted>5){const fine=Math.min(150,state.money);state.money-=fine;save();cancelMission(false);clearPolice();recover();toast('Busted. '+(fine?'€'+fine+' fine. ':'')+'Back on the road.',5);}}

function explodePlayer(reason){if(!incidents?.explode(state,state.elapsed,reason))return;state.speed=0;state.lateral=0;state.yawRate=0;state.health=0;state.spin=state.knockX=state.knockZ=0;keys.clear();if(state.car){state.car.health=0;state.car.mesh.visible=false;}toast(reason+' · Recovering nearby…',2);}
function kickActor(actor,vx,vz){actor.knockX=vx;actor.knockZ=vz;actor.spin=Math.sign(vx||1)*1.4;if(actor===state){state.health=Math.max(0,state.health-25);toast('Tram impact! Keep clear of the rails.',2);}else if(actor.health!==undefined)actor.health=Math.max(0,actor.health-25);}
function applyKnock(actor,dt){const spec=actor===state?state.car?.spec:actor.spec;if(!actor.knockX&&!actor.knockZ&&!actor.spin)return;const p=slideMove(actor,(actor.knockX||0)*dt,(actor.knockZ||0)*dt,spec?.width/2||.36,world.collision,actor.y);actor.x=p.x;actor.z=p.z;const yaw=actor.yaw+(actor.spin||0)*dt;if(!spec||!vehicleBlocked(actor.x,actor.z,yaw,world.collision,spec,actor.y))actor.yaw=yaw;actor.knockX=(actor.knockX||0)*Math.exp(-3*dt);actor.knockZ=(actor.knockZ||0)*Math.exp(-3*dt);actor.spin=(actor.spin||0)*Math.exp(-2*dt);if(actor!==state&&actor.mesh&&actor.spec)poseVehicle(actor);}
function movePlayer(dt){if(incidents?.recovery){state.speed=0;state.lateral=0;state.yawRate=0;if(state.elapsed>=incidents.recovery.until){incidents.recovery=null;if(state.car)state.car.mesh.visible=true;recover();toast('Vehicle recovered nearby. Continue exploring.');}return;}if(waterRecovery.active){falling(dt);return;}currentInput=drivingInput.sample(dt);const {forward:f,turn,boost}=currentInput;
 if(state.mode==='car'&&state.car.spec.aircraft){helicopterStep(state,{forward:f,turn,up:keys.has('Space'),down:boost},dt,terrain,world.collision);Object.assign(state.car,{x:state.x,z:state.z,y:state.y,yaw:state.yaw,speed:state.speed});poseVehicle(state.car);state.distance+=Math.abs(state.speed)*dt;return;}
 if(state.mode==='car'){const car=state.car,spec=car.spec,turbo=car.style==='cinquecento'&&keys.has('Tab');
 const result=advanceCar(state,state.health>0?currentInput:{forward:0,turn:0,brake:true,boost:false},dt,terrain,world.collision,turbo?{...spec,accel:spec.turboAccel,max:spec.turboMax}:spec,car.style);
 if(updateTurbo(car,state.speed,dt).explode){explodePlayer('Turbo overheated after 6 seconds');return;}
 if(result.hitSpeed>4&&collisionCooldown<=0){const response=impactResponse(result.hitSpeed);state.health=Math.max(0,state.health-response.damage);state.spin=(Math.sin(state.yaw)>=0?1:-1)*response.spin;if(response.destroy){explodePlayer('High-speed crash');return;}collisionCooldown=.7;playHit();}

 for(const c of cars){if(c===car)continue;const d=dist(c,state);if(c.mesh.visible&&d<(spec.length+c.spec.length)/2&&Math.abs((c.y||0)-state.y)<Math.max(spec.height,c.spec.height)&&vehiclesOverlap({...state,style:car.style},c)&&collisionCooldown<=0){const impact=Math.abs(state.speed-c.speed),response=impactResponse(impact);kickActor(c,Math.sin(state.yaw)*response.impulse,Math.cos(state.yaw)*response.impulse);state.spin=response.spin;if(response.destroy){explodePlayer('High-speed collision');return;}state.speed*=-.16;state.health=Math.max(0,state.health-impact*.35);c.speed=0;c.parked=true;collisionCooldown=1;playHit();if(impact>8){raiseWanted(Math.min(3,state.wanted+1));toast('Vehicle collision. Police alerted.');}}}
 car.x=state.x;car.z=state.z;car.yaw=state.yaw;car.health=state.health;car.speed=state.speed;state.y=terrain.height(state.x,state.z,state.y);poseVehicle(car);car.mesh.rotation.x+=state.pitch||0;car.mesh.rotation.z=-turn*Math.min(isBike(car.style)?.36:.025,Math.abs(state.speed)*(isBike(car.style)?.018:.001));state.distance+=Math.abs(state.speed)*dt;
 }else{
   const view=cameraRig.basis(f,turn), magnitude=Math.hypot(f,turn),speed=magnitude?(boost?7:3.6):0;
   const forward=magnitude?f/magnitude:0,side=magnitude?turn/magnitude:0;
   const dx=(Math.sin(view)*forward+Math.cos(view)*side)*speed*dt;
   const dz=(Math.cos(view)*forward-Math.sin(view)*side)*speed*dt;
   const moved=slideMove(state,dx,dz,.36,world.collision,Math.max(state.y,terrain.height(state.x+dx,state.z+dz,state.y)));
   state.speed=Math.hypot(moved.x-state.x,moved.z-state.z)/dt;
   state.x=moved.x;state.z=moved.z;
   if(magnitude)state.yaw+=angleDiff(Math.atan2(dx,dz),state.yaw)*(1-Math.exp(-14*dt));
   if(keys.has('Space')&&!jumpPressed&&state.y<=terrain.height(state.x,state.z,state.y)+.08){state.vy=5.7;jumpPressed=true;}
   if(!keys.has('Space'))jumpPressed=false;
   state.vy-=16*dt;const ground=terrain.height(state.x,state.z,state.y);state.y=Math.max(ground,state.y+state.vy*dt);if(state.y<=ground+.001)state.vy=0;
   placeFeet(player,state.x,state.y,state.z);player.rotation.y=state.yaw;
   const swing=state.speed>.1&&state.y<ground+.1?Math.sin(state.elapsed*(boost?13:8))*.55:0;
   player.userData.hips.children[0].rotation.x=swing;player.userData.hips.children[1].rotation.x=-swing;
   player.userData.arms.children[0].rotation.x=-swing*.8;player.userData.arms.children[1].rotation.x=swing*.8;
 }

 const waterY=terrain.waterAt(state.x,state.z,0,state.y);
 if(waterY!==null){if(waterRecovery.enter(Math.max(state.y,terrain.elevation(state.x,state.z)),waterY)){state.y=waterRecovery.y;state.speed=0;state.lateral=0;state.yawRate=0;keys.clear();document.body.classList.add('water-fall');toast('Water! Returning to dry land…',2);}}else waterRecovery.remember(state,terrain);
 const oldX=state.x,oldZ=state.z;state.x=clamp(state.x,PLAY_BOUNDS.minX,PLAY_BOUNDS.maxX);state.z=clamp(state.z,PLAY_BOUNDS.minZ,PLAY_BOUNDS.maxZ);if(oldX!==state.x||oldZ!==state.z){state.speed=0;state.lateral=0;state.yawRate=0;toast('Edge of this map. Turn back towards Padova.',2);}
}
function updateTraffic(dt,actors=[...cars,...cops]){const obstacles=state.mode==='foot'?[...actors,{...state,mesh:player}]:actors;for(const c of cars){
 if(c===state.car)continue;if(!c.mesh.visible){if(state.elapsed>(c.retryAt||0)){placeTraffic(c);c.retryAt=state.elapsed+2;}continue;}
 if(c.parked){poseVehicle(c);continue;}const density=DISTRICTS[districts?.at(c.x,c.z,c.road)||'urban'].traffic;if((cars.indexOf(c)%10)/10>Math.min(1,density)){c.mesh.visible=false;c.retryAt=state.elapsed+4;continue;}if(dist(c,state)>800){placeTraffic(c);continue;}
 if(c.speed<.2&&signals.allowed(c.target,state.elapsed,c.yaw)){c.jamTime=(c.jamTime||0)+dt;if(c.jamTime>18){placeTraffic(c,180,500);c.jamTime=0;continue;}}else c.jamTime=0;
 const node=graph.nodes[c.target],from=graph.nodes[c.prev];if(!node||!from){placeTraffic(c);continue;}
 c.road=from.edges.find(e=>e.id===c.target)?.road||c.road;const target=lanePoint(node,from,c.road);
 if(dist(c,target)<Math.max(2.5,Math.min(5,c.speed*.35))){const edges=node.edges.filter(e=>e.id!==c.prev&&e.road.k!=='pedestrian'&&e.road?.access!=='no'&&e.road?.access!=='private'&&(!c.spec||e.road.w>c.spec.width+1));const next=edges.length?edges:node.edges.filter(e=>!['no','private'].includes(e.road?.access)&&e.road.k!=='pedestrian'&&e.road.w>c.spec.width+1);if(next.length){const ranked=next.map(e=>({e,score:Math.random()*1.2-Math.abs(angleDiff(Math.atan2(graph.nodes[e.id].x-node.x,graph.nodes[e.id].z-node.z),c.yaw))*.25-cars.filter(o=>o!==c&&o.mesh.visible&&o.target===e.id).length*.35})).sort((a,b)=>b.score-a.score),edge=ranked[0].e;c.prev=c.target;c.target=edge.id;c.road=edge.road;}else{c.speed=0;c.stuck+=dt;}continue;}
 const yaw=Math.atan2(target.x-c.x,target.z-c.z),desired=trafficSpeed(c,target,obstacles,signals||{allowed:()=>true},state.elapsed);
 c.speed+=clamp(desired-c.speed,-c.spec.brake*dt,c.spec.accel*.55*dt);const newYaw=c.yaw+clamp(angleDiff(yaw,c.yaw),-1.8*dt,1.8*dt);
 const nx=c.x+Math.sin(newYaw)*c.speed*dt,nz=c.z+Math.cos(newYaw)*c.speed*dt;
 const lane=nearestOnSegment(nx,nz,[from.x,from.z],[node.x,node.z]),insideLane=dist(lane,{x:nx,z:nz})<=Math.max(.5,(c.road.w-c.spec.width)/2);
 if((insideLane||roadCorridor(nx,nz,c,graph,terrain))&&!vehicleBlocked(nx,nz,newYaw,world.collision,c.spec,terrain.height(nx,nz,c.y))&&terrain.dry(nx,nz,c.spec.width/2,c.y)){c.x=nx;c.z=nz;c.yaw=newYaw;c.stuck=desired>.5&&c.speed<.2?c.stuck+dt:0;}else{c.speed=0;c.stuck+=dt;if(c.stuck>5){c.yaw=newYaw;if(c.stuck>8)placeTraffic(c,180,500);}}poseVehicle(c);
}}
function updatePeople(dt,actors=[...cars,...cops]){for(const p of people){if(dist(p,state)>350||p.at<state.elapsed)placePerson(p);if(!p.mesh.visible)continue;if(state.mode==='car'&&!state.car.spec.aircraft&&dist(p,state)<1.7&&Math.abs(state.speed)>4&&collisionCooldown<=0){raiseWanted(Math.min(3,state.wanted+1));collisionCooldown=1;toast('Dangerous driving. Police alerted.');}
 const intent=pedestrianIntent(p,state.elapsed,actors,state,signals,graph);if(p.behavior==='group'){const leader=people.find(q=>q!==p&&q.behavior==='group'&&q.seed<p.seed&&q.mesh.visible&&dist(q,p)<30);if(leader){intent.yaw=Math.atan2(leader.x-p.x,leader.z-p.z);intent.speed=dist(p,leader)>2?1.4:0;}}p.yaw+=angleDiff(intent.yaw,p.yaw)*(1-Math.exp(-7*dt));
 const nx=p.x+Math.sin(p.yaw)*intent.speed*dt,nz=p.z+Math.cos(p.yaw)*intent.speed*dt,road=districts?.nearRoad(nx,nz,.1);
 const allowed=!collides(nx,nz,.4,world.collision,p.y)&&terrain.dry(nx,nz,.5,p.y)&&(!road||road.road.k==='pedestrian'||intent.crossing)&&dist({x:nx,z:nz},p.anchor||p)<45;
 if(allowed){p.x=nx;p.z=nz;p.blocked=0;}else{p.blocked=(p.blocked||0)+dt;if(p.blocked>.5){p.yaw+=Math.PI;p.roadYaw=p.yaw;p.blocked=0;p.crossGoal=null;}}
 p.speed=allowed?intent.speed:0;p.y=terrain.height(p.x,p.z,p.y);placeFeet(p.mesh,p.x,p.y,p.z);p.mesh.rotation.y=p.yaw;const a=p.speed>.1?Math.sin(state.elapsed*(p.speed>2?10:5)+p.seed)*.3:0;p.mesh.userData.hips.children[0].rotation.x=a;p.mesh.userData.hips.children[1].rotation.x=-a;
}}

function updateCamera(dt){
 if(!state.started){const a=state.elapsed*.026;camera.position.set(-170+Math.sin(a)*100,95,-70+Math.cos(a)*100);camera.lookAt(-170,12,-80);return;}
 const speed=Math.abs(state.speed);
 const targetFov=60+(reducedMotion.matches?0:Math.min(12,speed*.2));camera.fov+=(targetFov-camera.fov)*(1-Math.exp(-dt/(targetFov>camera.fov?.15:.5)));camera.updateProjectionMatrix();
 followYaw=cameraRig.update(dt,{mode:state.mode,yaw:state.yaw,speed:state.speed,time:state.elapsed});camPitch=cameraRig.pitch;
 const angle=followYaw;
 let d,h;
 if(state.camera===2){d=30;h=55;}
 else if(state.camera===1){d=state.mode==='car'?4:2.8;h=state.mode==='car'?2.7:2.15;}
 else{d=state.mode==='car'?10+speed*.08:5.8;h=(state.mode==='car'?4.5+speed*.025:2.8)+camPitch*2;}
 if(state.car){d+=Math.max(0,state.car.spec.length-4)*.9;h+=Math.max(0,state.car.spec.height-1.5)*.75;}
 if(state.camera!==2){h=1.5+Math.sin(camPitch)*d+(state.car?Math.max(0,state.car.spec.height-1.5)*.3:0);d*=Math.cos(camPitch);}
 const pose=visualPose(),anchor={x:pose.x,y:pose.y+(state.car?Math.max(1.5,state.car.spec.height*.65):1.5),z:pose.z};
 const desired=cameraBoom(anchor,{x:pose.x-Math.sin(angle)*d,y:pose.y+h,z:pose.z-Math.cos(angle)*d},world.collision);
 const smooth=camera.position.clone().lerp(new THREE.Vector3(desired.x,desired.y,desired.z),1-Math.exp(-dt*10));
 // Re-sweep AFTER smoothing: a safe endpoint alone does not make a safe path.
 const safe=cameraBoom(anchor,smooth,world.collision);
 camera.position.set(safe.x,Math.max(safe.y,terrain.height(safe.x,safe.z)+.5),safe.z);
 camera.lookAt(anchor.x,anchor.y,anchor.z);
 player.visible=state.mode==='foot'&&camera.position.distanceTo(new THREE.Vector3(anchor.x,anchor.y,anchor.z))>.8;
 sun.position.set(state.x-100,state.y+180,state.z+70);sun.target.position.set(state.x,state.y,state.z);sun.target.updateMatrixWorld();
}
function updateUI(){const turbo=state.car?.style==='cinquecento',remaining=turbo&&state.car.turboTime>0?Math.max(1,Math.ceil(6-state.car.turboTime)):null;$('turboStatus').hidden=!turbo;$('turboCountdown').textContent=remaining??'READY';$('turboStatus').dataset.critical=remaining?'true':'false';if($('touchTurbo'))$('touchTurbo').hidden=state.car?.style!=='cinquecento';const nearest=PLACES.reduce((a,b)=>dist(a,state)<dist(b,state)?a:b),road=nearestRoad(state,graph);$('location').textContent=dist(nearest,state)<220?nearest.name:road?.segment.road.n||'Padova';$('district').textContent=districts?DISTRICTS[districts.at(state.x,state.z,road?.segment.road)].label:'PADOVA';$('money').textContent=Math.floor(state.money).toLocaleString('en-GB');$('wanted').textContent='★'.repeat(state.wanted)+'☆'.repeat(5-state.wanted);$('wanted').style.opacity=state.escape>0?(Math.sin(state.elapsed*5)>0?.5:1):1;const kmh=Math.round(Math.abs(state.speed)*3.6),health=state.mode==='car'?state.health:100,rpm=state.mode==='car'?clamp(.9+Math.abs(state.speed)*.14+((keys.has('ShiftLeft')||keys.has('ShiftRight'))?1.2:0),.8,7.4):0,compass=['S','SE','E','NE','N','NW','W','SW'];$('speed').textContent=String(kmh).padStart(2,'0');$('vehicleName').textContent=state.mode==='car'?state.car.name.toUpperCase():'ON FOOT';$('gear').textContent=state.mode==='car'?(state.speed<-.4?'R':kmh<2?'N':String(Math.min(6,Math.max(1,Math.ceil(kmh/28))))):'—';$('rpm').style.width=(rpm/7.4*100)+'%';$('rpmValue').textContent=rpm.toFixed(1);$('altitude').textContent=Math.round(state.car?.spec.aircraft?state.y:terrain.elevation(state.x,state.z))+' M';$('gradient').textContent=state.car?(-Math.tan(terrain.slope(state.x,state.z,state.yaw,state.car.spec.wheelbase))*100).toFixed(1)+'%':'—';$('odometer').textContent=(state.distance/1000).toFixed(1)+' KM';$('heading').textContent=compass[Math.round((((state.yaw%(Math.PI*2))+Math.PI*2)%(Math.PI*2))/(Math.PI/4))%8];const nearbyTraffic=cars.filter(c=>c!==state.car&&dist(c,state)<300).length;$('trafficLevel').textContent=nearbyTraffic>12?'HIGH':nearbyTraffic>6?'MED':'LOW';$('health').style.width=health+'%';$('healthValue').textContent=Math.round(health)+'%';$('healthLabel').textContent=state.mode==='car'?'VEHICLE CONDITION':'SHIFT TO SPRINT';let hint='';if(state.mode==='foot'){const c=cars.find(c=>c.mesh.visible&&Math.abs((c.y||0)-state.y)<4&&dist(c,state)<6&&Math.abs(c.speed)<8);if(c&&c.mesh.visible)hint='E · Get in '+c.name;}else if(state.car?.spec.aircraft)hint='SPACE · Ascend / SHIFT · Descend / E · Exit after landing';else if(state.mission?.type==='delivery'&&dist(state,state.mission.target)<25)hint='Stop inside the gold marker';else if(state.health<=0)hint='R · Recover and repair';else if(state.busted>1)hint='MOVE! Police are about to catch you';$('interact').textContent=hint;$('interact').hidden=!hint;if(state.elapsed>toastUntil)$('toast').hidden=true;updateMissionUI();updateMarker();if(!currentTarget())$('targetDistance').hidden=true;drawMini();}

function setPaused(v){state.paused=v;clock.reset();previousPose=null;renderAlpha=1;keys.clear();drag=null;cameraRig.end(state.elapsed);drivingInput.reset();if(v&&engineAudio)engineAudio.mute();}
function showMenu(title,content){setPaused(true);$('menuTitle').textContent=title;$('menuContent').innerHTML=content;if(!$('menu').open)$('menu').showModal();}
function closeDialogs(){$('menu').close();$('mapDialog').close();setPaused(false);}
function activities(){if(!state.ready)return;let html='<div class="activities">';for(const [type,m] of Object.entries(missionTypes))html+='<button class="activity" data-mission="'+type+'"><span class="icon">'+({delivery:'◇',race:'⚑',escape:'★'}[type])+'</span><span><b>'+m.title+'</b><small>'+m.desc+'</small></span><span class="reward">'+m.reward+'</span></button>';html+='</div>';if(state.mode!=='car')html+='<p class="about-copy">Get in a car with <kbd>E</kbd> before accepting a job.</p>';if(state.mission)html+='<div class="menu-actions"><button id="cancelJob">Cancel current activity</button></div>';showMenu('A little extra on the side.',html);document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>{if(state.mode!=='car'){closeDialogs();toast('Get in the nearby car with E, then press J.');return;}beginMission(b.dataset.mission);});if($('cancelJob'))$('cancelJob').onclick=()=>{cancelMission();closeDialogs();};}
function pauseMenu(){if(!state.ready)return;showMenu('Take a breather.','<div class="controls-grid"><span><kbd>W / S</kbd> accelerate / reverse</span><span><kbd>A / D</kbd> steer / move sideways</span><span><kbd>E</kbd> enter / leave vehicle</span><span><kbd>V</kbd> choose a vehicle</span><span><kbd>SPACE</kbd> brake / jump</span><span><kbd>SHIFT</kbd> boost / sprint</span><span><kbd>TAB</kbd> Cinquecento special turbo</span><span><kbd>C</kbd> cycle camera</span><span><kbd>M</kbd> city map</span><span><kbd>J</kbd> activities</span><span><kbd>R</kbd> recover & repair</span><span>On foot: WASD follows the camera. Drag to look.</span></div><div class="settings"><label for="quality">Graphics</label><select id="quality"><option value="low">Performance</option><option value="medium">Balanced</option><option value="high">Detailed</option></select><button id="soundBtn" class="textbutton">Sound: '+(state.sound?'on':'off')+'</button></div><p class="about-copy">'+state.jobs+' jobs completed · €'+Math.floor(state.money)+' earned<br>Progress is saved on this browser. Traffic density updates after reloading.<br>Scene: '+renderer.info.render.calls+' draw calls · '+Math.round(renderer.info.render.triangles/1000)+'k triangles.</p><div class="menu-actions"><button class="primary" id="resumeBtn">'+(state.started?'Back to the streets':'Close')+'</button><button id="recoverBtn">Recover vehicle</button><button id="fullscreenBtn">Full screen</button><button id="vehiclesBtn">Choose a vehicle</button><button id="worldInfoBtn">About the world</button></div>');$('quality').value=state.quality;$('quality').onchange=e=>{state.quality=e.target.value;applyQuality();save();};$('resumeBtn').onclick=closeDialogs;$('recoverBtn').onclick=()=>{recover();closeDialogs();};$('fullscreenBtn').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Use your browser’s full-screen control.');}};$('worldInfoBtn').onclick=about;$('vehiclesBtn').onclick=vehiclesMenu;$('soundBtn').onclick=()=>{state.sound=!state.sound;if(state.sound)initAudio();$('soundBtn').textContent='Sound: '+(state.sound?'on':'off');};}
function about(){const buildings=(data?.buildingCount||data?.buildings.length||88000).toLocaleString('en-GB');showMenu('Padova, at street scale.','<div class="about-copy"><p><strong>A playable, stylised reconstruction of Padua.</strong> '+buildings+' mapped building footprints, real streets, waterways and parks across a roughly 13 × 13 km area. One metre in the map is one metre in the game.</p><p>Street geometry and building footprints come from <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap contributors</a> (ODbL). Building heights are estimated where the map has no height data. Facades and landmark details are interpretive. Terrain follows an offline, smoothed elevation grid without exaggeration. Bridge ramps and river levels are approximate. Water causes a fall and automatic recovery; bridges remain usable.</p><p>Elevation: <a href="https://github.com/tilezen/joerd/blob/master/docs/attribution.md" target="_blank" rel="noopener">Mapzen Terrain Tiles · Copernicus EU-DEM · USGS</a>. <a href="./data/terrain.json" download>Download the derived terrain data</a>.</p><p>Buildings with supplied GLB models replace their map extrusions automatically. The remaining city is still approximate; a complete photographic centre is not included.</p><p>This version has outdoor exploration, driving, traffic, courier jobs, checkpoint races and police pursuits. It does not contain photographic buildings, enterable interiors, multiplayer or GTA’s full systems.</p><p>Best on a MacBook with a keyboard. Use <strong>Performance</strong> graphics if movement feels slow. Drag on the scene to look around; no mouse lock needed.</p><p>Built with <a href="https://threejs.org" target="_blank" rel="noopener">Three.js</a> · <a href="./data/padova.json" download>Download the derived map data</a> · <a href="./model-guide.html" target="_blank" rel="noopener">Add real buildings</a></p></div><div class="menu-actions"><button class="primary" id="aboutClose">Back</button></div>');$('aboutClose').onclick=closeDialogs;}
function openMap(){if(!state.ready)return;setPaused(true);$('mapPlaces').innerHTML='<span class="eyebrow">JUMP TO A PLACE</span>'+PLACES.map((p,i)=>'<button data-place="'+i+'">'+p.name+'<small>'+p.tag+'</small></button>').join('')+'<button id="clearWaypoint">Clear waypoint</button>';$('mapPlaces').querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>travel(PLACES[Number(b.dataset.place)]));$('clearWaypoint').onclick=()=>{state.waypoint=null;if(!state.mission)state.route=[];drawFullMap();};drawFullMap();$('mapDialog').showModal();mapReady?.then(()=>{if($('mapDialog').open)drawFullMap();});}
$('fullmap').onclick=e=>{const r=$('fullmap').getBoundingClientRect();const size=Math.min(r.width,r.height),offsetX=(r.width-size)/2,offsetY=(r.height-size)/2,px=e.clientX-r.left-offsetX,py=e.clientY-r.top-offsetY;if(px<0||py<0||px>size||py>size)return;if(state.mission){toast('Finish or cancel your activity to set a waypoint.');return;}const p={x:minBounds.x+px/size*minBounds.w,z:minBounds.z+py/size*minBounds.h,name:'Waypoint'};state.waypoint=safeTarget(p);routeTo(state.waypoint);drawFullMap();};
function applyQuality(){world?.setQuality(state.quality);if(renderer){renderer.setPixelRatio(Math.min(devicePixelRatio,state.quality==='low'?1:state.quality==='high'?1.7:1.25));renderer.shadowMap.enabled=state.quality!=='low';renderer.setSize(innerWidth,innerHeight);scene.fog.far=state.quality==='low'?900:state.quality==='high'?1950:1400;camera.far=scene.fog.far+150;camera.updateProjectionMatrix();}}
function initAudio(){if(engineAudio){engineAudio.ctx.resume().catch(()=>{});return;}try{engineAudio=new EngineAudio();engineAudio.ctx.resume().catch(()=>{});}catch{state.sound=false;}}
function playHit(){if(state.sound){initAudio();engineAudio?.hit(state.speed);}}

function start(){if(!state.ready)return;state.started=true;state.paused=false;previousPose=null;clock.reset();$('intro').hidden=true;$('playingUI').hidden=false;state.elapsed=0;lastUi=-1;followYaw=state.yaw;cameraRig.reset(state.yaw);camera.position.set(state.x-8,state.y+7,state.z-9);if(!multiplayer?.connected){if(state.mode==='foot')toggleVehicle();if(ensureCar()){beginMission('delivery');toast('Your first delivery. Drive to the gold marker. WASD or gamepad; Space / A to handbrake.',6);}}}
$('playBtn').onclick=start;$('pauseBtn').onclick=pauseMenu;$('activityBtn').onclick=activities;$('mapBtn').onclick=openMap;$('closeMenu').onclick=closeDialogs;$('closeMap').onclick=closeDialogs;$('aboutBtn').onclick=about;$('touchCar').onclick=toggleVehicle;$('vehicleMenuBtn').onclick=vehiclesMenu;
for(const d of [$('menu'),$('mapDialog')])d.addEventListener('cancel',()=>setPaused(false));
window.addEventListener('keydown',e=>{if(e.code==='Tab'&&state.started&&!state.paused&&state.car?.style==='cinquecento')e.preventDefault();if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code)&&state.started&&!state.paused)e.preventDefault();if(e.repeat)return;if(state.paused){if(e.code==='Escape'){e.preventDefault();closeDialogs();}return;}if(e.code==='Escape'){if(state.started)pauseMenu();return;}if(e.code==='Enter'&&!state.started){start();return;}if(!state.started)return;keys.add(e.code);if(e.code==='KeyE')toggleVehicle();if(e.code==='KeyC'){state.camera=(state.camera+1)%3;toast(['Chase camera','Close camera','Aerial camera'][state.camera],1.5);}if(e.code==='KeyV')vehiclesMenu();if(e.code==='KeyJ')activities();if(e.code==='KeyM')openMap();if(e.code==='KeyR')recover();});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();if(state.started&&!state.paused)pauseMenu();});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();if(state.started&&!state.paused)pauseMenu();}});
canvas.addEventListener('pointerdown',e=>{if(!state.started||state.paused||drag)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};cameraRig.begin();canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;cameraRig.drag(e.clientX-drag.x,e.clientY-drag.y);drag={id:e.pointerId,x:e.clientX,y:e.clientY};});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{if(drag&&e.pointerId===drag.id){drag=null;cameraRig.end(state.elapsed);}});canvas.addEventListener('contextmenu',e=>e.preventDefault());
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();keys.add(b.dataset.key);b.setPointerCapture(e.pointerId);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.key));});
window.addEventListener('resize',()=>{if(!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});

function simulate(dt){
 const actors=[...cars,...cops];
 previousPose={x:state.x,y:state.y,z:state.z,mode:state.mode};
 for(const a of [...cars,...people,...cops])previousActors.set(a.mesh,{x:a.x,z:a.z,y:a.mesh.position.y,yaw:a.yaw});
 for(const c of cars)if(c.spec.aircraft&&c.mesh.visible){const running=c===state.car;c.mesh.userData.rotor.rotation.y+=dt*(running?35:1);c.mesh.userData.tailRotor.rotation.x+=dt*(running?45:1);}
 state.elapsed+=dt;collisionCooldown=Math.max(0,collisionCooldown-dt);
 if(state.started&&multiplayer?.connected){currentInput=drivingInput.sample(dt);const pose=multiplayer.step(currentInput);if(pose){Object.assign(state,pose);Object.assign(state.car,pose);poseVehicle(state.car);state.distance+=Math.abs(state.speed)*dt;}return;}
 if(state.started){applyKnock(state,dt);for(const a of [...cars,...people,...cops])if(a!==state.car)applyKnock(a,dt);movePlayer(dt);updateTraffic(dt,actors);updatePeople(dt,actors);trams?.update(dt,state.elapsed,state,[state,...cars.filter(c=>c!==state.car),...people,...cops],kickActor);incidents?.update(state.elapsed);if(!waterRecovery.active&&!incidents?.recovery){updatePolice(dt);updateMission(dt);}
   if(state.waypoint&&!state.mission&&dist(state,state.waypoint)<15){state.waypoint=null;state.route=[];toast('You’ve reached your waypoint.');}
 }
}
function animate(time){
 requestAnimationFrame(animate);
 const rawFrameMs=frameTime?Math.max(0,time-frameTime):1000/60;
 const dt=frameTime?Math.min(.15,Math.max(0,(time-frameTime)/1000)):1/60;frameTime=time;
 if(!state.ready)return;frame++;
 if(multiplayer?.connected){multiplayer.prediction?.visual(dt);updateRemotes();}
 if(!state.paused){
   renderAlpha=clock.advance(dt,simulate);
   const pose=visualPose();if(state.mode==='foot')placeFeet(player,pose.x,pose.y,pose.z);
   for(const a of [...cars,...people,...cops]){const prev=previousActors.get(a.mesh);if(!prev||dist(prev,a)>10)continue;a.mesh.position.x=THREE.MathUtils.lerp(prev.x,a.x,renderAlpha);a.mesh.position.z=THREE.MathUtils.lerp(prev.z,a.z,renderAlpha);const y=a.spec?.aircraft?THREE.MathUtils.lerp(prev.y,a.y,renderAlpha):a===state.car&&waterRecovery.active?pose.y:terrain.height(a.mesh.position.x,a.mesh.position.z,a===state.car?state.y:a.y);a.mesh.position.y=y-(a.mesh.userData.soleHeight||0);a.mesh.rotation.y=prev.yaw+angleDiff(a.yaw,prev.yaw)*renderAlpha;}
   if(multiplayer?.connected&&state.car)state.car.mesh.position.set(pose.x,pose.y,pose.z);
   // Chunk creation runs once per render, never inside the catch-up loop.
   if(!benchmark)world.update(state.started?state.x:-150,state.started?state.z:-49,false,state.started?600:Infinity);
   if(state.started&&!benchmark){requestBuildingTiles(state.x,state.z);pumpBuildingTiles(time);}
   modelLayer?.update(state.x,state.z);
   updateCamera(dt);signals?.update(scene,terrain,state.x,state.z,state.elapsed);
   if(marker){marker.children[1].position.y=7+Math.sin(state.elapsed*2)*.7;marker.children[1].rotation.y=state.elapsed*.6;}
   if(state.elapsed-lastUi>.12){updateUI();lastUi=state.elapsed;}
   if(engineAudio)engineAudio.update(state,currentInput,state.sound&&state.mode==='car'&&!waterRecovery.active,cops);
 }
 crowd?.update();
 if(!state.paused)drivingEffects?.update(state,dt,terrain,reducedMotion.matches);
 benchmark?.before(time,camera,world,terrain);
 renderer.render(scene,camera);
 benchmark?.after(time,renderer,rawFrameMs);
}

async function init(){try{progress(5,'Loading the city map…');const [mapLoad,terrainResponse]=await Promise.all([loadMap(),fetch('./data/terrain.json')]);if(!terrainResponse.ok)throw new Error('Terrain download failed');const terrainData=await terrainResponse.json();data=mapLoad.map;mapStream=mapLoad.stream;for(const key of mapLoad.initialTileKeys)integratedBuildingTiles.add(key);progress(55,'Laying out the nearby buildings…');await yieldFrame();
 scene=new THREE.Scene();scene.background=new THREE.Color('#b7c9c6');scene.fog=new THREE.Fog('#b7c9c6',250,1400);camera=new THREE.PerspectiveCamera(60,innerWidth/innerHeight,.12,1600);renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
 progress(57,'Lighting the evening sky…');await yieldFrame();console.time('v2 atmosphere');setupAtmosphere(scene,renderer);console.timeEnd('v2 atmosphere');scene.add(new THREE.HemisphereLight('#b8d6df','#655341',1.25));sun=new THREE.DirectionalLight('#ffdfac',3.4);sun.position.set(-100,180,800);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-85;sun.shadow.camera.right=85;sun.shadow.camera.top=85;sun.shadow.camera.bottom=-85;sun.shadow.camera.near=1;sun.shadow.camera.far=450;sun.shadow.bias=-.001;sun.shadow.normalBias=.3;scene.add(sun,sun.target);const cityResponse=await fetch('./data/city.json');if(!cityResponse.ok)throw new Error('City transport data unavailable');applyCityData(data,await cityResponse.json());applyMapCorrections(data);progress(60,'Loading road surfaces…');await yieldFrame();console.time('v2 roads');districts=new Districts(data);terrain=new Terrain(terrainData,data,{modern:true,roadCache:mapLoad.roadCache});terrain.districts=districts;console.timeEnd('v2 roads');progress(65,'Building the neighbourhoods…');await yieldFrame();console.time('v2 world');world=new CityWorld(scene,data,terrain);console.timeEnd('v2 world');mapStream.release(mapLoad.initialTileKeys);modelLayer=new BuildingModels(scene,world);await modelLayer.init();applyQuality();progress(70,'Connecting streets and traffic…');await yieldFrame();graph=makeRoadGraph(data.roads,{separateLevels:true});patrolGraph=makeRoadGraph(data.roads.filter(r=>r.w>=4&&r.k!=='pedestrian'&&!['no','private'].includes(r.access)),{separateLevels:true});signals=new TrafficSignals(graph,data.signals);trams=new Trams(scene,data,terrain);incidents=new Incidents(scene);player=createPerson('#d9bf8f');scene.add(player);drivingEffects=new DrivingEffects(scene);createPopulation();crowd=new CrowdBatch(scene,people);world.update(state.x,state.z,true);progress(85,'Preparing the nearby streets…');await yieldFrame();if(!benchmark)mapReady=makeMap().catch(error=>console.warn('Map preview unavailable',error));
 marker=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(11,.27,8,48),new THREE.MeshBasicMaterial({color:'#ffcb72'}));ring.rotation.x=Math.PI/2;const arrow=new THREE.Mesh(new THREE.OctahedronGeometry(1.8),new THREE.MeshStandardMaterial({color:'#ffc56a',emissive:'#8b5d1f',emissiveIntensity:.3}));arrow.position.y=7;marker.add(ring,arrow);const beam=new THREE.Mesh(new THREE.CylinderGeometry(2,10,26,24,1,true),new THREE.MeshBasicMaterial({color:'#ffc56a',transparent:true,opacity:.045,depthWrite:false,side:THREE.DoubleSide}));beam.position.y=13;marker.add(beam);marker.visible=false;scene.add(marker);progress(100,'Ready. '+(data.buildingCount||data.buildings.length).toLocaleString('en-GB')+' mapped buildings · nearby tiles loaded');state.ready=true;$('playBtn').disabled=false;$('playBtn').textContent='Enter the city  →';updateUI();requestAnimationFrame(animate);
 }catch(e){mapStream?.close();console.error(e);progress(100,'');$('loadingText').className='fatal';$('loadingText').textContent='The city could not start. '+(String(e).includes('WebGL')?'Enable WebGL / hardware acceleration in your browser and reload.':'Check your connection and reload to try again.');$('playBtn').textContent='Reload city';$('playBtn').disabled=false;$('playBtn').onclick=()=>location.reload();}}
function updateRemotes(){
 const visible=new Set();for(const pose of multiplayer.remotes()){visible.add(pose.id);let mesh=remoteMeshes.get(pose.id);if(!mesh){mesh=compactCar(createVehicle('mito',['#e9c475','#71b9b1','#cf7773','#8ea3d4'][pose.id%4]));scene.add(mesh);remoteMeshes.set(pose.id,mesh);}mesh.position.set(pose.x,pose.y,pose.z);mesh.rotation.y=pose.yaw;}
 for(const [id,mesh] of remoteMeshes)if(!visible.has(id)){scene.remove(mesh);disposeObject(mesh);remoteMeshes.delete(id);}
}
function setupMultiplayer(){
 multiplayer=new MultiplayerClient({terrain,collision:world.collision,
  onStatus:text=>{$('networkStatus').textContent=text;$('networkMessage').textContent=text;},
  onJoin:pose=>{cancelMission(false);clearPolice();for(const car of cars)car.mesh.visible=false;for(const person of people)person.mesh.visible=false;player.visible=false;const car=addCar(pose.x,pose.z,pose.yaw,false,true,'mito');Object.assign(state,pose,{mode:'car',car,mission:null,waypoint:null,route:[]});Object.assign(car,pose);poseVehicle(car);waterRecovery.reset();incidents.recovery=null;$('networkDialog').close();start();setPaused(false);},
  onLeave:()=>{for(const mesh of remoteMeshes.values()){scene.remove(mesh);disposeObject(mesh);}remoteMeshes.clear();for(const person of people)person.mesh.visible=true;toast('Returned to single-player.');}
 });
}
$('onlineBtn').onclick=()=>{if(!state.ready)return;setPaused(true);$('networkDialog').showModal();};
$('closeNetwork').onclick=()=>{$('networkDialog').close();setPaused(false);};
$('networkDialog').addEventListener('cancel',()=>setPaused(false));
$('leaveNetwork').onclick=()=>{multiplayer?.close();$('networkDialog').close();setPaused(false);};
$('networkForm').addEventListener('submit',event=>{event.preventDefault();try{if(!multiplayer)setupMultiplayer();multiplayer.connect($('serverAddress').value,$('roomCode').value);}catch(error){$('networkMessage').textContent=error.message;}});

init();
