import {batchStatic} from './static-batch.js';
import * as THREE from '../../dist/vendor/three.module.js';
import {dist,nearestOnSegment,clamp} from '../sim/core.js';

// Build routes only from mapped operational rails; do not use planned lines.
export function tramRoutes(tracks){const nodes=[],lookup=new Map();const node=p=>{const k=p.join(',');if(!lookup.has(k)){lookup.set(k,nodes.length);nodes.push({x:p[0],z:p[1],edges:[]});}return lookup.get(k);};for(const r of tracks)for(let i=1;i<r.p.length;i++){const a=node(r.p[i-1]),b=node(r.p[i]);if(a===b)continue;const d=dist(nodes[a],nodes[b]);nodes[a].edges.push({id:b,d,road:r});nodes[b].edges.push({id:a,d,road:r});}
 const seen=new Set(),routes=[];for(let seed=0;seed<nodes.length;seed++){if(seen.has(seed))continue;const ids=[seed];seen.add(seed);for(let i=0;i<ids.length;i++)for(const e of nodes[ids[i]].edges)if(!seen.has(e.id)){seen.add(e.id);ids.push(e.id);}if(ids.length<10)continue;
  const south=ids.reduce((a,b)=>nodes[a].z>nodes[b].z?a:b),north=ids.reduce((a,b)=>nodes[a].z<nodes[b].z?a:b),scores=new Map([[south,0]]),previous=new Map(),open=new Set([south]);
  while(open.size){let id=-1,best=Infinity;for(const n of open)if(scores.get(n)<best){best=scores.get(n);id=n;}open.delete(id);if(id===north)break;for(const e of nodes[id].edges){const value=best+e.d;if(value<(scores.get(e.id)??Infinity)){scores.set(e.id,value);previous.set(e.id,id);open.add(e.id);}}}
  if(!previous.has(north))continue;const route=[north];while(route[0]!==south)route.unshift(previous.get(route[0]));const points=route.map(id=>({x:nodes[id].x,z:nodes[id].z})),lengths=[0];for(let i=1;i<points.length;i++)lengths.push(lengths.at(-1)+dist(points[i-1],points[i]));if(lengths.at(-1)>700)routes.push({points,lengths,roads:route.slice(1).map((id,i)=>nodes[route[i]].edges.find(e=>e.id===id).road),length:lengths.at(-1)});
 }return routes.sort((a,b)=>b.length-a.length);}
export function sampleRail(route,d){d=clamp(d,0,route.length);let lo=0,hi=route.lengths.length-1;while(lo+1<hi){const mid=(lo+hi)>>1;if(route.lengths[mid]<d)lo=mid;else hi=mid;}const a=route.points[lo],b=route.points[hi],t=(d-route.lengths[lo])/Math.max(.001,route.lengths[hi]-route.lengths[lo]);return {road:route.roads?.[lo],x:a.x+(b.x-a.x)*t,z:a.z+(b.z-a.z)*t,yaw:Math.atan2(b.x-a.x,b.z-a.z)};}
function body(){const g=new THREE.Group(),add=(color,x,y,z,w,h,d)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.65}));m.position.set(x,y,z);g.add(m);return m;};add('#7498ac',0,1.25,0,2.35,2.35,8.5);add('#d0d7d3',0,2.53,0,2.3,.2,8.1);add('#253b48',0,1.85,4.27,2.1,.9,.025);for(const side of [-1,1]){add('#243e4c',side*1.185,1.8,0,.025,.85,7.7);for(const z of [-2.8,0,2.8])add('#9eafb1',side*1.2,1.3,z,.03,1.8,.08);}add('#f2e8be',0,.85,4.29,1.65,.15,.04);batchStatic(g,{spatial:false});return g;}
export class Trams{
 constructor(scene,map,terrain){this.terrain=terrain;this.routes=tramRoutes(map.tracks||[]);this.vehicles=[];this.scene=scene;for(const route of this.routes.slice(0,3)){route.stops=[];for(const stop of map.stops||[]){let best=null,distance=Infinity;for(let i=1;i<route.points.length;i++){const a=route.points[i-1],b=route.points[i],q=nearestOnSegment(...stop.p,[a.x,a.z],[b.x,b.z]),d=Math.hypot(q.x-stop.p[0],q.z-stop.p[1]);if(d<distance){distance=d;best=route.lengths[i-1]+dist(a,b)*q.t;}}if(distance<12&&!route.stops.some(d=>Math.abs(d-best)<30))route.stops.push(best);}for(let i=0;i<Math.min(4,Math.ceil(route.length/2500));i++){const cars=[body(),body()];cars.forEach(g=>scene.add(g));const tram={route,d:route.length*(i+.25)/4,direction:i%2?1:-1,speed:0,dwell:0,lastStop:-1,cars};this.vehicles.push(tram);for(let j=0;j<cars.length;j++){const pose=sampleRail(route,tram.d-j*8.65*tram.direction),g=cars[j];g.position.set(pose.x,pose.road?terrain.roads.sample(pose.road,pose.x,pose.z)+.05:terrain.height(pose.x,pose.z),pose.z);g.rotation.y=pose.yaw+(tram.direction<0?Math.PI:0);}}}
 }
 update(dt,time,player,actors,kick){for(const tram of this.vehicles){const before=tram.d;if(tram.dwell>0){tram.dwell-=dt;tram.speed=0;}else{const approaching=tram.route.stops.find(d=>Math.abs(d-tram.d)<18&&Math.sign(d-tram.d)===tram.direction&&d!==tram.lastStop);tram.speed=Math.min(approaching===undefined?10:4,tram.speed+dt*1.3);tram.d+=tram.speed*dt*tram.direction;if(approaching!==undefined&&Math.abs(approaching-tram.d)<1){tram.lastStop=approaching;tram.dwell=4;}if(tram.d<4.3||tram.d>tram.route.length-4.3){tram.d=clamp(tram.d,4.3,tram.route.length-4.3)-8.65*tram.direction;tram.cars.reverse();tram.direction*=-1;tram.lastStop=-1;tram.dwell=3;}}
  for(let i=0;i<2;i++){const pose=sampleRail(tram.route,tram.d-i*8.65*tram.direction),g=tram.cars[i];g.visible=dist(pose,player)<700;g.position.set(pose.x,pose.road?this.terrain.roads.sample(pose.road,pose.x,pose.z)+.05:this.terrain.height(pose.x,pose.z,g.position.y),pose.z);g.rotation.y=pose.yaw+(tram.direction<0?Math.PI:0);if(!g.visible)continue;
   for(const actor of actors){if(actor.mesh&&!actor.mesh.visible||actor.tramHitUntil>time||Math.abs((actor.y??g.position.y)-g.position.y)>3)continue;const dx=actor.x-pose.x,dz=actor.z-pose.z,side=dx*Math.cos(pose.yaw)-dz*Math.sin(pose.yaw),along=dx*Math.sin(pose.yaw)+dz*Math.cos(pose.yaw);if(Math.abs(side)<1.5+(actor.spec?.width||actor.car?.spec.width||.7)/2&&Math.abs(along)<4.5+(actor.spec?.length||actor.car?.spec.length||.7)/2){actor.tramHitUntil=time+1.2;kick(actor,Math.cos(pose.yaw)*(side<0?-1:1)*18,-Math.sin(pose.yaw)*(side<0?-1:1)*18);}}
  }
 }}
}
